name: Android Emulator

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test_group1:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome
        options: --shm-size=2gb

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Enable KVM
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Appium and UIAutomator2 driver
        run: |
          npm install -g appium
          appium driver install uiautomator2

      - name: Start Appium Server
        run: |
          appium --base-path /wd/hub --relaxed-security &

      - name: Verify Appium server is running
        run: |
          curl http://localhost:4723/wd/hub/status


      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 30   # Версия Android 11.0
            target: google_apis
            arch: x86_64
            device: pixel_8_pro  # Устройство Pixel 8 Pro
            ndk: 21.0.6113669
            cmake: 3.10.2.4988404
            script: |
              adb wait-for-device
              adb shell input keyevent 82
              adb devices
              pytest tests_dev/payments_tests/test_payment_taxes.py::TestTaxes::test_payment_taxes_page_inn_have_arrears
      

      - name: check folders with screenshot
        if: always()
        run: |
          echo "Listing files in the current directory:" && ls
          echo "Changing directory to artifacts:" && cd artifacts
          echo "Listing files in artifacts directory:" && ls
          echo "Changing directory to screenshots:" && cd screenshots
          echo "Listing files in screenshots directory:" && ls

      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-screenshots
          path: artifacts/screenshots
